[project]
name = "draw-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.18.0",
    "matplotlib>=3.10.7",
    "openpyxl>=3.1.5",
    "polars>=1.35.1",
]

[dependency-groups]
dev = ["ruff>=0.14.3"]
